import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/navbar";
import Sidebar from "@/components/sidebar";
import { Suspense } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          <Header />
          <div className="flex flex-1">
            <Sidebar />
            <Suspense fallback={<div>Loading...</div>}>
              <main className="flex-1 p-4">{children}</main>
            </Suspense>
          </div>
        </div>
      </body>
    </html>
  );
}
